### ISSUE TITLE
How to have custom Nicola key bindings

### ISSUE THREAD

**Issue by ElnuDev** [fcitx/fcitx5-anthy#8]
In the settings, there are fields for "Custom Key Binding," "Custom Romaji Table," "Custom Kana Table," and "Custom Nicola Table, but there's no indication for how these fields are supposed to be used. In particular, I am using Nicola, and I'd like to bind my `-` key to a lengthener `ー` (which should be the default?) and it's staying just as a normal hyphen. Previously, I used anthy under ibus and I was able to remap my Nicola keys, but here I see no indication of how to do this. Thanks in advance!

**Comment by wengxt** [comment]
Currently it's binding to − (U+2212), which is defined in https://github.com/fcitx/fcitx5-anthy/blob/master/src/default_tables.cpp#L890

The reset of items in the list are defined in https://github.com/fcitx/fcitx5-anthy/tree/master/profile , which is also located under /usr/share/fcitx5/anthy on your system.

The "Custom" field are file name to the .sty file like  the built-in files above. It can be either absolute path, or relative path that relative to XDG_DATA_DIR/fcitx5/anthy .

The definition of these rules are from scim-anthy, since it was originally forked from it. 

The character you want is ー (U+30FC).

So, you can make a copy of .sty file (e.g., https://github.com/fcitx/fcitx5-anthy/blob/master/profile/nicola-a.sty), put it under ~/.local/share/fcitx5/anthy/[some name].sty , then use the combobox to select "custom" and put the [some name].sty there.

**Comment by ElnuDev** [comment]
I've copied one of the Nicola tables there calling it `nicola.sty`, switched to Custom, and tried both the relative and absolute path of the .sty, but in both cases fcitx5 immediately crashes when I apply the changes and Anthy gets removed from my input list. After that if I try to re-add it and access its settings, the settings window is blank and the "restore defaults" button does nothing, so I had to manually restore the configuration file. Any ideas what's going wrong? Thanks for the help!

**Comment by wengxt** [comment]
Sorry for the inconvenience, found typo which may cause overflow when loading the custom table.

You might want to try master, or, alternatively, a quick workaround for you is to create "nicola-a.sty" in the user directory and select nicola-a. That will also load the user level config.

**Comment by ElnuDev** [comment]
Thank you! I've switched to master and it's working now, I really appreciate the help. Thank you for fcitx5-anthy!
